apiVersion: v2
name: bruno-site
description: Bruno Lucena's personal portfolio and homelab showcase website
type: application
version: 0.1.13
appVersion: "1.0.0"
keywords:
  - portfolio
  - homelab
  - react
  - golang
  - kubernetes
home: https://lucena.cloud
sources:
  - https://github.com/brunovlucena/bruno-site
maintainers:
  - name: Bruno Lucena
    email: bruno@lucena.cloud
    url: https://lucena.cloud
