apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheus-rule.yaml

commonLabels:
  app.kubernetes.io/name: statuspage-exporter
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: homelab
  app.kubernetes.io/managed-by: flux
