apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: homelab-infrastructure
  namespace: flux-system

resources:
  - repositories
  - sealed-secrets
  - cert-manager # TODO: Alerts
  - cloudflare-tunnel # TODO Alerts - temporarily disabled due to deployment issues
  - metrics-server
  - prometheus-operator
  - homepage # TODO: Review alerts
  - loki
  - alloy
  - tempo
  - k6-operator
  - agent-legacy
  - agent-sre
  - grafana-mcp
  - statuspage-exporter
  # - notifi-test # TODO: Fix Linkerd Server conflicts
  

