apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system

resources:
  - helmrelease.yaml
  - ai.yaml
  - buoyant-license.yaml
  - cloudflare.yaml
  - ghcr-secret.yaml
  - ghcr-secret-agent-sre.yaml
  - ghcr-secret-agent-legacy.yaml
  - ai-secrets-agent-sre.yaml
  - ai-secrets-agent-legacy.yaml
